Uses setuptools>44.1.0 in tox
setuptools>44.1.0 is required to install pdbpp on Python 2.7 in Travis.

This fix the error

    SyntaxError: invalid syntax

when install pdbpp on tox with Python 2.7. Fix job

https://travis-ci.org/github/plone/bobtemplates.plone/jobs/744855819